version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: lottery
      POSTGRES_PASSWORD: lottery
      POSTGRES_DB: lottery
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  service-predict:
    build: ./service-predict
    ports: ["8000:8000"]
    depends_on: [db, redis]
    environment:
      DATABASE_URL: postgresql://lottery:lottery@db:5432/lottery
      REDIS_URL: redis://redis:6379

  service-crawler:
    build: ./service-crawler
    ports: ["9001:9001"]
    depends_on: [redis]

  gateway:
    build: ./gateway
    ports: ["8080:8080"]
    depends_on: [service-predict, service-crawler]

volumes:
  pgdata:
